# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(max_length=255, unique=True, verbose_name='we vote id for the Apple ID owner')),
                ('user_code', models.CharField(max_length=255, verbose_name="User's apple id code")),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='apple email address')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's first_name from Apple")),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's middle_name from Apple")),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's last_name from Apple")),
                ('apple_platform', models.CharField(blank=True, max_length=32, null=True, verbose_name='Platform of Apple Device')),
                ('apple_os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='Apple OS Version')),
                ('apple_model', models.CharField(blank=True, max_length=32, null=True, verbose_name='Apple Device Model')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_last_referenced', models.DateTimeField(auto_now=True, verbose_name='date last referenced')),
            ],
        ),
    ]
