# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctcl_id_temp', models.CharField(max_length=255, null=True, unique=True, verbose_name='temporary ctcl id')),
                ('we_vote_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='permanent we vote id')),
                ('electoral_district_name', models.CharField(max_length=255, null=True, verbose_name='electoral district name')),
                ('electoral_district_type', models.CharField(choices=[('borough', 'borough'), ('city', 'city'), ('city_council', 'city-council'), ('congressional', 'congressional'), ('county', 'county'), ('county-council', 'county-council'), ('judicial', 'judicial'), ('municipality', 'municipality'), ('national', 'national'), ('school', 'school'), ('special', 'special'), ('state', 'state'), ('state-house', 'state-house'), ('state-senate', 'state-senate'), ('town', 'town'), ('township', 'township'), ('utility', 'utility'), ('village', 'village'), ('ward', 'ward'), ('water', 'water'), ('other', 'other')], default='state', max_length=16, verbose_name='electoral district type')),
                ('electoral_district_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='electoral district number')),
                ('electoral_district_other_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Allows for cataloging a new DistrictType option when Type is specified as other')),
                ('ocd_id_external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ocd id external identifier')),
                ('ballotpedia_district_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ballotpedia_district_kml', models.URLField(blank=True, max_length=255, null=True, verbose_name='url of kml file on ballotpedia')),
                ('ballotpedia_district_latitude', models.FloatField(null=True, verbose_name='latitude')),
                ('ballotpedia_district_longitude', models.FloatField(null=True, verbose_name='longitude')),
                ('ballotpedia_district_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ballotpedia_district_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='url of district on ballotpedia')),
                ('ballotpedia_district_ocd_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ocd id identifier')),
                ('geo_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='us census geo id')),
                ('nces_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='school nces id')),
                ('state_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='state code')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralDistrictLinkToPollingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_location_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('electoral_district_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('ballotpedia_district_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
                ('state_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='state code')),
            ],
        ),
    ]
