# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowCampaignX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaignx_id', models.PositiveIntegerField(blank=True, null=True)),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='FollowIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('issue_id', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('following_status', models.CharField(choices=[('FOLLOWING', 'Following'), ('STOP_FOLLOWING', 'Not Following'), ('FOLLOW_IGNORE', 'Ignoring'), ('STOP_IGNORING', 'Not Ignoring')], db_index=True, default='FOLLOWING', max_length=15)),
                ('is_follow_visible_publicly', models.BooleanField(default=False, verbose_name='')),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='FollowIssueList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FollowOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('organization_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('voter_linked_organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='organization we vote permanent id')),
                ('organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('following_status', models.CharField(choices=[('FOLLOWING', 'Following'), ('STOP_FOLLOWING', 'Not Following'), ('FOLLOW_IGNORE', 'Ignoring'), ('STOP_IGNORING', 'Not Ignoring')], db_index=True, default='FOLLOWING', max_length=15)),
                ('auto_followed_from_twitter_suggestion', models.BooleanField(default=False, verbose_name='')),
                ('is_follow_visible_publicly', models.BooleanField(default=False, verbose_name='')),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='FollowOrganizationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedIssueToFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='voter we vote id')),
                ('issue_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='issue we vote id')),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedOrganizationToFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='voter we vote id person 1')),
                ('organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='organization we vote id person 2')),
                ('from_twitter', models.BooleanField(default=False, verbose_name='from twitter')),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
    ]
