# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInternalCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(blank=True, default='', max_length=255)),
                ('election_id_list_serialized', models.TextField(default='')),
                ('cached_api_response_serialized', models.TextField(default='')),
                ('date_cached', models.DateTimeField(auto_now_add=True, null=True)),
                ('replaced', models.BooleanField(default=False)),
                ('date_replaced', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiRefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_id_list_serialized', models.TextField(blank=True, null=True)),
                ('date_scheduled', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_refresh_is_needed', models.DateTimeField(null=True)),
                ('date_checked_out', models.DateTimeField(null=True)),
                ('date_refresh_completed', models.DateTimeField(null=True)),
                ('refresh_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
