# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOutboundDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_sms_template', models.CharField(choices=[('SIGN_IN_CODE_SMS_TEMPLATE', 'Send code to verify sign in.')], default='SIGN_IN_CODE_SMS_TEMPLATE', max_length=50)),
                ('sender_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sender')),
                ('sender_voter_sms', models.CharField(blank=True, max_length=50, null=True, verbose_name='sms address for sender')),
                ('recipient_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the recipient if we have it')),
                ('recipient_sms_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='sms we vote id for recipient')),
                ('recipient_voter_sms', models.CharField(blank=True, max_length=50, null=True, verbose_name='sms address for recipient')),
                ('template_variables_in_json', models.TextField(blank=True, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='SMSPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote id of this sms address')),
                ('voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sms owner')),
                ('normalized_sms_phone_number', models.CharField(max_length=50, verbose_name='sms address')),
                ('sms_ownership_is_verified', models.BooleanField(default=False)),
                ('sms_permanent_bounce', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='secret key to verify ownership of sms')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMSScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, null=True)),
                ('sender_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sender')),
                ('sender_voter_sms', models.CharField(blank=True, max_length=50, null=True, verbose_name='sender sms address')),
                ('recipient_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the recipient')),
                ('recipient_sms_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sms')),
                ('recipient_voter_sms', models.CharField(blank=True, max_length=50, null=True, verbose_name='recipient sms address')),
                ('send_status', models.CharField(choices=[('TO_BE_PROCESSED', 'Message to be processed'), ('BEING_SENT', 'Message being sent'), ('SENT', 'Message sent')], default='TO_BE_PROCESSED', max_length=50)),
                ('sms_description_id', models.PositiveIntegerField(default=0, verbose_name='the internal id of SMSOutboundDescription')),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
    ]
