# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_location_id', models.CharField(max_length=255, verbose_name='vip polling_location id')),
                ('we_vote_id', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id of this map point')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='location name')),
                ('polling_hours_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='polling hours')),
                ('directions_text', models.TextField(blank=True, null=True, verbose_name='directions to get to map point')),
                ('line1', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='address line 1 returned from VIP')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2 returned from VIP')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='city returned from VIP')),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='state returned from VIP')),
                ('zip_long', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='raw text zip returned from VIP, 9 characters')),
                ('county_name', models.CharField(default=None, max_length=255, null=True)),
                ('precinct_name', models.CharField(default=None, max_length=255, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('ctcl_error_count', models.PositiveIntegerField(default=None, null=True)),
                ('google_response_address_not_found', models.PositiveIntegerField(default=None, null=True, verbose_name="how many times Google can't find address")),
                ('vote_usa_error_count', models.PositiveIntegerField(default=None, null=True)),
                ('no_contests_count', models.PositiveIntegerField(default=None, null=True)),
                ('source_code', models.CharField(default=None, max_length=50, null=True)),
                ('successful_retrieve_count', models.PositiveIntegerField(default=None, null=True)),
                ('use_for_bulk_retrieve', models.BooleanField(default=False, verbose_name='this provides geographical coverage')),
                ('polling_location_deleted', models.BooleanField(default=False, verbose_name='removed from usage')),
            ],
        ),
        migrations.CreateModel(
            name='PollingLocationLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('google_civic_election_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('is_from_ballotpedia', models.BooleanField(db_index=True, default=False, null=True)),
                ('is_from_ctcl', models.BooleanField(db_index=True, default=False, null=True)),
                ('is_from_vote_usa', models.BooleanField(db_index=True, default=False, null=True)),
                ('kind_of_log_entry', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('log_entry_deleted', models.BooleanField(db_index=True, default=False)),
                ('log_entry_message', models.TextField(null=True)),
                ('polling_location_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('text_for_map_search', models.CharField(max_length=255, null=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
    ]
