# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id')),
                ('campaign_description', models.TextField(blank=True, null=True)),
                ('campaign_title', models.CharField(max_length=255, verbose_name='title of campaign')),
                ('final_election_date_as_integer', models.PositiveIntegerField(db_index=True, null=True)),
                ('in_draft_mode', models.BooleanField(db_index=True, default=True)),
                ('is_ok_to_promote_on_we_vote', models.BooleanField(db_index=True, default=True)),
                ('is_blocked_by_we_vote', models.BooleanField(db_index=True, default=False)),
                ('is_blocked_by_we_vote_reason', models.TextField(blank=True, null=True)),
                ('is_in_team_review_mode', models.BooleanField(db_index=True, default=False)),
                ('is_not_promoted_by_we_vote', models.BooleanField(db_index=True, default=False)),
                ('is_not_promoted_by_we_vote_reason', models.TextField(blank=True, null=True)),
                ('is_still_active', models.BooleanField(db_index=True, default=True)),
                ('is_victorious', models.BooleanField(db_index=True, default=False)),
                ('politician_starter_list_serialized', models.TextField(blank=True, null=True)),
                ('seo_friendly_path', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('started_by_voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('supporters_count', models.PositiveIntegerField(default=0)),
                ('supporters_count_minimum_ignored', models.BooleanField(db_index=True, default=False)),
                ('supporters_count_victory_goal', models.PositiveIntegerField(default=0)),
                ('we_vote_hosted_campaign_photo_original_url', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_campaign_photo_large_url', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_campaign_photo_medium_url', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_campaign_photo_small_url', models.TextField(blank=True, null=True)),
                ('date_campaign_started', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignXListedByOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('site_owner_organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_requested_by_voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visible_to_public', models.BooleanField(default=False)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignXNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('organization_we_vote_id', models.CharField(max_length=255, null=True)),
                ('speaker_name', models.CharField(max_length=255, null=True)),
                ('campaign_news_subject', models.TextField(null=True)),
                ('campaign_news_text', models.TextField(null=True)),
                ('in_draft_mode', models.BooleanField(db_index=True, default=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(null=True)),
                ('visibility_blocked_by_we_vote', models.BooleanField(default=False)),
                ('visible_to_public', models.BooleanField(default=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_sent_to_email', models.DateTimeField(db_index=True, null=True)),
                ('we_vote_id', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignXOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='date last changed')),
                ('feature_this_profile_image', models.BooleanField(default=True)),
                ('order_in_list', models.PositiveIntegerField(null=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('visible_to_public', models.BooleanField(default=False)),
                ('voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignXPolitician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('next_election_date_as_integer', models.PositiveIntegerField(db_index=True, null=True)),
                ('politician_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('politician_name', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=2, null=True, verbose_name='politician home state')),
                ('we_vote_hosted_profile_image_url_large', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(blank=True, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignXSEOFriendlyPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_we_vote_id', models.CharField(max_length=255, null=True)),
                ('campaign_title', models.CharField(max_length=255)),
                ('base_pathname_string', models.CharField(max_length=255, null=True)),
                ('pathname_modifier', models.CharField(max_length=10, null=True)),
                ('final_pathname_string', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignXSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_supported', models.BooleanField(db_index=True, default=True)),
                ('campaignx_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('is_subscribed_by_email', models.BooleanField(default=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('organization_we_vote_id', models.CharField(max_length=255, null=True)),
                ('supporter_name', models.CharField(max_length=255, null=True)),
                ('supporter_endorsement', models.TextField(null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(null=True)),
                ('visibility_blocked_by_we_vote', models.BooleanField(default=False)),
                ('visible_to_public', models.BooleanField(default=False)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('date_supported', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
    ]
