# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id of this issue')),
                ('issue_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='name of the issue')),
                ('issue_description', models.TextField(blank=True, default='', null=True, verbose_name='description of the issue')),
                ('issue_followers_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='number of followers of this issue')),
                ('linked_organization_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='number of organizations linked to the issue')),
                ('hide_issue', models.BooleanField(default=True)),
                ('considered_left', models.BooleanField(default=False)),
                ('considered_right', models.BooleanField(default=False)),
                ('issue_icon_local_path', models.TextField(blank=True, default='', null=True, verbose_name='path in web app for the issue icon')),
                ('we_vote_hosted_image_url_large', models.URLField(blank=True, null=True, verbose_name='we vote hosted large image url')),
                ('we_vote_hosted_image_url_medium', models.URLField(blank=True, null=True, verbose_name='we vote hosted medium image url')),
                ('we_vote_hosted_image_url_tiny', models.URLField(blank=True, null=True, verbose_name='we vote hosted tiny image url')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLinkToIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('issue_id', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id')),
                ('link_active', models.BooleanField(default=True, verbose_name='')),
                ('reason_for_link', models.CharField(choices=[('NO_REASON', 'No reason'), ('LINKED_BY_ORGANIZATION', 'Linked by organization'), ('LINKED_BY_WE_VOTE', 'Linked by We Vote'), ('AUTO_LINKED_BY_HASHTAG', 'Auto-linked by hashtag'), ('AUTO_LINKED_BY_TEXT', 'Auto-linked by text')], default='NO_REASON', max_length=25)),
                ('link_blocked', models.BooleanField(default=False, verbose_name='')),
                ('reason_link_is_blocked', models.CharField(choices=[('NO_REASON', 'No reason'), ('BLOCKED_BY_ORGANIZATION', 'Blocked by organization'), ('BLOCKED_BY_WE_VOTE', 'Blocked by We Vote'), ('FLAGGED_BY_VOTERS', 'Flagged by voters')], default='NO_REASON', max_length=25)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
    ]
