# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAuthResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_device_id', models.CharField(max_length=255, unique=True, verbose_name='voter_device_id initiating Twitter Auth')),
                ('datetime_of_authorization', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('twitter_id', models.BigIntegerField(blank=True, null=True, verbose_name='twitter big integer id')),
                ('twitter_screen_name', models.CharField(max_length=255, null=True, verbose_name='twitter screen name / handle')),
                ('twitter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='display name from twitter')),
                ('twitter_profile_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of logo from twitter')),
                ('twitter_profile_banner_url_https', models.URLField(blank=True, null=True, verbose_name='url of banner from twitter')),
                ('twitter_request_token', models.TextField(blank=True, null=True, verbose_name='twitter request token')),
                ('twitter_request_secret', models.TextField(blank=True, null=True, verbose_name='twitter request secret')),
                ('twitter_access_token', models.TextField(blank=True, null=True, verbose_name='twitter access token')),
                ('twitter_access_secret', models.TextField(blank=True, null=True, verbose_name='twitter access secret')),
            ],
        ),
    ]
