# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_handle', models.CharField(default='', max_length=15, verbose_name="twitter handle of this tweet's author")),
                ('twitter_id', models.BigIntegerField(default=0, verbose_name="twitter user's id of this tweet's author")),
                ('tweet_id', models.BigIntegerField(default=0, verbose_name="id of this tweet's author")),
                ('is_retweet', models.BooleanField(default=False, verbose_name='is this a retweet?')),
                ('tweet_text', models.CharField(default='', max_length=280, verbose_name='text field from twitter tweet api')),
                ('date_published', models.DateTimeField(null=True, verbose_name='date published')),
                ('organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id')),
            ],
        ),
        migrations.CreateModel(
            name='TweetFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0, verbose_name="id of this tweet's author")),
                ('favorited_by_handle', models.CharField(max_length=15, verbose_name='twitter handle of person who favorited this tweet')),
                ('date_favorited', models.DateTimeField(null=True, verbose_name='date favorited')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterCursorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id_of_me', models.BigIntegerField(verbose_name='twitter id of viewer')),
                ('twitter_api_name', models.CharField(max_length=255, verbose_name='twitter api name')),
                ('twitter_next_cursor', models.BigIntegerField(verbose_name='twitter next cursor state')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterLinkPossibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_campaign_we_vote_id', models.CharField(max_length=255, verbose_name='candidate we vote id')),
                ('search_term_used', models.CharField(max_length=255, verbose_name='')),
                ('twitter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='display name from twitter')),
                ('not_a_match', models.BooleanField(default=False, verbose_name='')),
                ('likelihood_score', models.IntegerField(null=True, verbose_name='')),
                ('twitter_id', models.BigIntegerField(null=True, verbose_name='twitter big integer id')),
                ('twitter_handle', models.CharField(max_length=255, null=True, verbose_name='twitter screen name / handle')),
                ('twitter_profile_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of logo from twitter')),
                ('twitter_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text description of this organization from twitter.')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='url of website from twitter account')),
                ('twitter_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location from twitter')),
                ('twitter_followers_count', models.IntegerField(blank=True, default=0, verbose_name='number of twitter followers')),
                ('twitter_utc_offset', models.IntegerField(blank=True, default=0, null=True, verbose_name='utc_offset from twitter')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterLinkToOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_we_vote_id', models.CharField(max_length=255, unique=True, verbose_name='we vote id for the org owner')),
                ('twitter_id', models.BigIntegerField(null=True, unique=True, verbose_name='twitter big integer id')),
                ('date_last_changed', models.DateTimeField(auto_now=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterLinkToVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(max_length=255, unique=True, verbose_name='we vote id for the voter owner')),
                ('twitter_id', models.BigIntegerField(unique=True, verbose_name='twitter big integer id')),
                ('secret_key', models.CharField(max_length=255, unique=True, verbose_name='secret key to verify ownership twitter account')),
                ('date_last_changed', models.DateTimeField(auto_now=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.BigIntegerField(blank=True, null=True, verbose_name='twitter big integer id')),
                ('twitter_handle', models.CharField(max_length=255, unique=True, verbose_name='twitter screen name / handle')),
                ('twitter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='display name from twitter')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name="url of user's website")),
                ('twitter_profile_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of logo from twitter')),
                ('twitter_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location from twitter')),
                ('twitter_followers_count', models.IntegerField(blank=True, default=0, verbose_name='number of twitter followers')),
                ('twitter_profile_background_image_url_https', models.URLField(blank=True, null=True, verbose_name='tile-able background from twitter')),
                ('twitter_profile_banner_url_https', models.URLField(blank=True, null=True, verbose_name='profile banner image from twitter')),
                ('we_vote_hosted_profile_image_url_large', models.URLField(blank=True, null=True, verbose_name='we vote hosted large image url')),
                ('we_vote_hosted_profile_image_url_medium', models.URLField(blank=True, null=True, verbose_name='we vote hosted medium image url')),
                ('we_vote_hosted_profile_image_url_tiny', models.URLField(blank=True, null=True, verbose_name='we vote hosted tiny image url')),
                ('twitter_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text description of this organization from twitter.')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterWhoFollowMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_of_me', models.CharField(max_length=15, verbose_name="from this twitter handle's perspective...")),
                ('handle_that_follows_me', models.CharField(max_length=15, verbose_name="twitter handle of this tweet's author")),
            ],
        ),
        migrations.CreateModel(
            name='TwitterWhoIFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id_of_me', models.BigIntegerField(verbose_name='twitter id of viewer')),
                ('twitter_id_i_follow', models.BigIntegerField(verbose_name='twitter id of the friend')),
            ],
        ),
    ]
