# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectedOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id for this elected office')),
                ('elected_office_name', models.CharField(max_length=255, verbose_name='name of the elected office')),
                ('elected_office_name_es', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name of the elected office in Spanish')),
                ('google_civic_elected_office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='elected_office name exactly as received from google civic')),
                ('google_civic_election_id', models.PositiveIntegerField(default=0, verbose_name='google civic election id')),
                ('ocd_division_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ocd division id')),
                ('maplight_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='maplight unique identifier')),
                ('ballotpedia_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ballotpedia unique identifier')),
                ('wikipedia_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='wikipedia unique identifier')),
                ('number_elected', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic number of candidates who will be elected')),
                ('state_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='state this elected_office serves')),
                ('primary_party', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='district name')),
                ('district_scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic district scope')),
                ('district_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic district id')),
                ('contest_level0', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 0')),
                ('contest_level1', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 1')),
                ('contest_level2', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 2')),
                ('electorate_specifications', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('special', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('ctcl_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='ctcl uuid')),
                ('elected_office_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='elected_office description')),
                ('elected_office_description_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='elected_office description in Spanish')),
                ('elected_office_is_partisan', models.BooleanField(default=False, verbose_name='elected_office is_partisan')),
            ],
        ),
    ]
