# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnovIOApiCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_action', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('kind_of_action', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('number_of_items_sent_in_query', models.PositiveIntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnovIOApiCounterDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_action', models.DateField(verbose_name='date of action')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call')),
            ],
        ),
        migrations.CreateModel(
            name='SnovIOApiCounterMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('month_of_action', models.SmallIntegerField(verbose_name='number of the month')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call')),
            ],
        ),
        migrations.CreateModel(
            name='SnovIOApiCounterWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('week_of_action', models.SmallIntegerField(verbose_name='number of the week')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call')),
            ],
        ),
    ]
