# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id_temp', models.CharField(max_length=255, null=True, unique=True, verbose_name='temporary party id')),
                ('we_vote_id', models.CharField(max_length=32, null=True, unique=True, verbose_name='party we_vote_id')),
                ('party_name', models.CharField(max_length=255, verbose_name='party name')),
                ('party_abbreviation', models.CharField(blank=True, max_length=255, null=True, verbose_name='party abbreviation')),
                ('ctcl_uuid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='ctcl uuid')),
            ],
        ),
    ]
