# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_set_id', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='batch set id')),
                ('candidate_selection_id', models.CharField(default='', max_length=255, null=True, verbose_name='candidate selection id')),
                ('contest_office_id', models.CharField(default='', max_length=255, null=True, verbose_name='contest office ctcl id')),
            ],
        ),
        migrations.CreateModel(
            name='CTCLApiCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_action', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('kind_of_action', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='kind of call to CTCL')),
                ('google_civic_election_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='google civic election id')),
            ],
        ),
        migrations.CreateModel(
            name='CTCLApiCounterDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_action', models.DateField(verbose_name='date of action')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to CTCL')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
            ],
        ),
        migrations.CreateModel(
            name='CTCLApiCounterMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('month_of_action', models.SmallIntegerField(verbose_name='number of the month')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to CTCL')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
            ],
        ),
        migrations.CreateModel(
            name='CTCLApiCounterWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('week_of_action', models.SmallIntegerField(verbose_name='number of the week')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to CTCL')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
            ],
        ),
    ]
