# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='the text for a single hashtag')),
                ('twitter_handle', models.CharField(blank=True, max_length=15, null=True, verbose_name='twitter handle that we want to link to something')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='text that might be found in a tweet')),
            ],
        ),
    ]
