# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeVoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='voter we vote permanent id')),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='candidate we vote permanent id')),
                ('organization_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='organization we vote permanent id')),
                ('issue_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='issue we vote permanent id')),
                ('google_civic_election_id', models.PositiveIntegerField(default=0, verbose_name='google civic election id')),
                ('facebook_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='facebook big integer id')),
                ('facebook_profile_image_url_https', models.TextField(blank=True, null=True, verbose_name='url of profile image from facebook')),
                ('facebook_background_image_url_https', models.TextField(blank=True, null=True, verbose_name='url of background image from facebook')),
                ('facebook_background_image_offset_x', models.IntegerField(blank=True, default=0, null=True, verbose_name='x offset of facebook cover image')),
                ('facebook_background_image_offset_y', models.IntegerField(blank=True, default=0, null=True, verbose_name='y offset of facebook cover image')),
                ('maplight_id', models.BigIntegerField(blank=True, null=True, verbose_name='maplight big integer id')),
                ('maplight_image_url_https', models.TextField(blank=True, null=True, verbose_name='image url from maplight')),
                ('vote_smart_id', models.BigIntegerField(blank=True, null=True, verbose_name='vote smart big integer id')),
                ('vote_smart_image_url_https', models.TextField(blank=True, null=True, verbose_name='image url from vote smart')),
                ('twitter_id', models.BigIntegerField(blank=True, null=True, verbose_name='twitter big integer id')),
                ('twitter_profile_banner_url_https', models.TextField(blank=True, null=True, verbose_name='profile banner image from twitter')),
                ('twitter_profile_background_image_url_https', models.TextField(blank=True, null=True, verbose_name='tile-able background from twitter')),
                ('twitter_profile_image_url_https', models.TextField(blank=True, null=True, verbose_name='url of logo from twitter')),
                ('issue_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of issue image')),
                ('ballotpedia_profile_image_url', models.TextField(blank=True, null=True, verbose_name='profile image from ballotpedia')),
                ('campaignx_photo_url_https', models.TextField(blank=True, null=True)),
                ('chosen_favicon_image_url_https', models.URLField(blank=True, null=True, verbose_name='org favicon image')),
                ('chosen_logo_image_url_https', models.URLField(blank=True, null=True, verbose_name='org logo image')),
                ('chosen_social_share_master_image_url_https', models.URLField(blank=True, null=True, verbose_name='org master share image')),
                ('linkedin_profile_image_url', models.TextField(blank=True, null=True, verbose_name='profile image from linkedin')),
                ('photo_url_from_ctcl', models.TextField(blank=True, null=True)),
                ('photo_url_from_vote_usa', models.TextField(blank=True, null=True)),
                ('voter_uploaded_profile_image_url_https', models.TextField(blank=True, null=True)),
                ('wikipedia_profile_image_url', models.TextField(blank=True, null=True, verbose_name='profile image from wikipedia')),
                ('other_source', models.TextField(blank=True, null=True, verbose_name='other source of image')),
                ('other_source_image_url', models.TextField(blank=True, null=True, verbose_name='other source url of image')),
                ('source_image_still_valid', models.BooleanField(default=False, verbose_name='is the url of source image still valid')),
                ('image_height', models.BigIntegerField(blank=True, null=True, verbose_name='height of image in pixel')),
                ('image_width', models.BigIntegerField(blank=True, null=True, verbose_name='width of image in pixel')),
                ('we_vote_image_url', models.TextField(blank=True, null=True, verbose_name='url of image on AWS')),
                ('we_vote_image_file_location', models.TextField(blank=True, null=True, verbose_name='image file path on AWS')),
                ('we_vote_parent_image_id', models.BigIntegerField(blank=True, null=True, verbose_name='Local id of parent image')),
                ('date_image_saved', models.DateTimeField(auto_now_add=True, verbose_name='date when image saved on wevote')),
                ('same_day_image_version', models.BigIntegerField(blank=True, null=True, verbose_name='image version on same day')),
                ('is_active_version', models.BooleanField(default=False, verbose_name='True if image is newest')),
                ('kind_of_image_ballotpedia_profile', models.BooleanField(default=False, verbose_name='image is ballotpedia')),
                ('kind_of_image_ctcl_profile', models.BooleanField(default=False)),
                ('kind_of_image_campaignx_photo', models.BooleanField(default=False)),
                ('kind_of_image_chosen_favicon', models.BooleanField(default=False, verbose_name='image is for favicon')),
                ('kind_of_image_chosen_logo', models.BooleanField(default=False, verbose_name='image is for header')),
                ('kind_of_image_chosen_social_share_master', models.BooleanField(default=False, verbose_name='image is for sharing')),
                ('kind_of_image_facebook_profile', models.BooleanField(default=False, verbose_name='image is facebook profile')),
                ('kind_of_image_facebook_background', models.BooleanField(default=False, verbose_name='image is facebook background')),
                ('kind_of_image_issue', models.BooleanField(default=False, verbose_name='image is for issue')),
                ('kind_of_image_linkedin_profile', models.BooleanField(default=False, verbose_name='image is linkedin')),
                ('kind_of_image_maplight', models.BooleanField(default=False, verbose_name='image is maplight')),
                ('kind_of_image_other_source', models.BooleanField(default=False, verbose_name='image is from other sources')),
                ('kind_of_image_twitter_background', models.BooleanField(default=False, verbose_name='image is twitter background')),
                ('kind_of_image_twitter_banner', models.BooleanField(default=False, verbose_name='image is twitter banner')),
                ('kind_of_image_twitter_profile', models.BooleanField(default=False, verbose_name='image is twitter profile')),
                ('kind_of_image_vote_smart', models.BooleanField(default=False, verbose_name='image is vote smart')),
                ('kind_of_image_vote_usa_profile', models.BooleanField(default=False)),
                ('kind_of_image_voter_uploaded_profile', models.BooleanField(default=False, verbose_name='image was uploaded')),
                ('kind_of_image_wikipedia_profile', models.BooleanField(default=False, verbose_name='image is wikipedia')),
                ('kind_of_image_original', models.BooleanField(default=False, verbose_name='is image size original')),
                ('kind_of_image_large', models.BooleanField(default=False, verbose_name='is image size large')),
                ('kind_of_image_medium', models.BooleanField(default=False, verbose_name='is image size medium')),
                ('kind_of_image_tiny', models.BooleanField(default=False, verbose_name='is image size tiny')),
            ],
        ),
    ]
