# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_campaign_we_vote_id', models.CharField(max_length=255, verbose_name='candidate we vote id')),
                ('search_term_used', models.CharField(max_length=255, verbose_name='')),
                ('item_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='searched item title')),
                ('item_link', models.URLField(blank=True, null=True, verbose_name='url where searched item pointing')),
                ('item_snippet', models.CharField(blank=True, max_length=1024, null=True, verbose_name='searched item snippet')),
                ('item_image', models.URLField(blank=True, null=True, verbose_name='image url for searched item')),
                ('item_formatted_url', models.URLField(blank=True, null=True, verbose_name='item formatted url')),
                ('item_meta_tags_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='searched item meta tags description')),
                ('search_request_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='search request url')),
                ('from_ballotpedia', models.BooleanField(default=False, verbose_name='searched link from ballotpedia')),
                ('from_facebook', models.BooleanField(default=False, verbose_name='searched link from facebook')),
                ('from_linkedin', models.BooleanField(default=False, verbose_name='searched link from linkedin')),
                ('from_twitter', models.BooleanField(default=False, verbose_name='searched link from twitter')),
                ('from_wikipedia', models.BooleanField(default=False, verbose_name='searched link from wikipedia')),
                ('not_a_match', models.BooleanField(default=False, verbose_name='this candidate does not match')),
                ('likelihood_score', models.IntegerField(null=True, verbose_name='score for a match')),
                ('chosen_and_updated', models.BooleanField(default=False, verbose_name='when search detail updated in candidate table')),
                ('facebook_search_found', models.BooleanField(default=False, verbose_name='user found from facebook search')),
                ('facebook_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name from facebook search')),
                ('facebook_emails', models.CharField(blank=True, max_length=255, null=True, verbose_name='emails from facebook')),
                ('facebook_about', models.CharField(blank=True, max_length=255, null=True, verbose_name='about from facebook')),
                ('facebook_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location from facebook')),
                ('facebook_photos', models.CharField(blank=True, max_length=1024, null=True, verbose_name='photos from facebook')),
                ('facebook_bio', models.CharField(blank=True, max_length=1024, null=True, verbose_name='bio from facebook')),
                ('facebook_general_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='general information from facebook')),
                ('facebook_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='description from facebook')),
                ('facebook_features', models.CharField(blank=True, max_length=255, null=True, verbose_name='features from facebook')),
                ('facebook_contact_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact address from facebook')),
                ('facebook_mission', models.CharField(blank=True, max_length=1024, null=True, verbose_name='mission from facebook')),
                ('facebook_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category from facebook')),
                ('facebook_website', models.URLField(blank=True, null=True, verbose_name='website from facebook')),
                ('facebook_personal_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='personal information from facebook')),
                ('facebook_personal_interests', models.CharField(blank=True, max_length=255, null=True, verbose_name='personal interests from facebook')),
                ('facebook_posts', models.CharField(blank=True, max_length=1024, null=True, verbose_name='posts from facebook')),
            ],
        ),
    ]
