# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id of this politician')),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='last name')),
                ('politician_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='official full name')),
                ('google_civic_candidate_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='full name from google civic')),
                ('google_civic_candidate_name2', models.CharField(max_length=255, null=True)),
                ('google_civic_candidate_name3', models.CharField(max_length=255, null=True)),
                ('full_name_assembled', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='full name assembled from first_name + last_name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('N', 'Gender Neutral'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='gender')),
                ('birth_date', models.DateField(blank=True, default=None, null=True, verbose_name='birth date')),
                ('bioguide_id', models.CharField(max_length=200, null=True, unique=True, verbose_name='bioguide unique identifier')),
                ('thomas_id', models.CharField(max_length=200, null=True, unique=True, verbose_name='thomas unique identifier')),
                ('lis_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='lis unique identifier')),
                ('govtrack_id', models.CharField(max_length=200, null=True, unique=True, verbose_name='govtrack unique identifier')),
                ('opensecrets_id', models.CharField(max_length=200, null=True, verbose_name='opensecrets unique identifier')),
                ('vote_smart_id', models.CharField(max_length=200, null=True, verbose_name='votesmart unique identifier')),
                ('fec_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='fec unique identifier')),
                ('cspan_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='cspan unique identifier')),
                ('wikipedia_id', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='wikipedia url')),
                ('ballotpedia_id', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='ballotpedia url')),
                ('house_history_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='house history unique identifier')),
                ('maplight_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='maplight unique identifier')),
                ('washington_post_id', models.CharField(max_length=200, null=True, verbose_name='washington post unique identifier')),
                ('icpsr_id', models.CharField(max_length=200, null=True, verbose_name='icpsr unique identifier')),
                ('political_party', models.CharField(max_length=255, null=True, verbose_name='politician political party')),
                ('state_code', models.CharField(max_length=2, null=True, verbose_name='politician home state')),
                ('politician_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='latest website url of politician')),
                ('politician_twitter_handle', models.CharField(max_length=255, null=True, verbose_name='politician twitter screen_name')),
                ('vote_usa_politician_id', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Vote USA permanent id for this candidate')),
                ('we_vote_hosted_profile_image_url_large', models.URLField(blank=True, null=True, verbose_name='we vote hosted large image url')),
                ('we_vote_hosted_profile_image_url_medium', models.URLField(blank=True, null=True, verbose_name='we vote hosted medium image url')),
                ('we_vote_hosted_profile_image_url_tiny', models.URLField(blank=True, null=True, verbose_name='we vote hosted tiny image url')),
                ('ctcl_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='ctcl uuid')),
                ('politician_facebook_id', models.CharField(max_length=255, null=True, verbose_name='politician facebook user name')),
                ('politician_phone_number', models.CharField(max_length=255, null=True, verbose_name='politician phone number')),
                ('politician_googleplus_id', models.CharField(max_length=255, null=True, verbose_name='politician googleplus profile name')),
                ('politician_youtube_id', models.CharField(max_length=255, null=True, verbose_name='politician youtube profile name')),
                ('politician_email_address', models.CharField(max_length=80, null=True, verbose_name='politician email address')),
                ('date_last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='PoliticiansAreNotDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician1_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='first politician we are tracking')),
                ('politician2_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='second politician we are tracking')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticianTagLinkDisputed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='politician.politician', verbose_name='politician unique identifier')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tag.tag', verbose_name='tag unique identifier')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticianTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='politician.politician', verbose_name='politician unique identifier')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tag.tag', verbose_name='tag unique identifier')),
            ],
        ),
        migrations.AddField(
            model_name='politician',
            name='tag_link',
            field=models.ManyToManyField(through='politician.PoliticianTagLink', to='tag.Tag'),
        ),
    ]
