# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote id of this email address')),
                ('voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the email owner')),
                ('normalized_email_address', models.EmailField(max_length=255, verbose_name='email address')),
                ('email_ownership_is_verified', models.BooleanField(default=False)),
                ('email_permanent_bounce', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='secret key to verify ownership of email')),
                ('subscription_secret_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOutboundDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_email_template', models.CharField(choices=[('GENERIC_EMAIL_TEMPLATE', 'Generic Email'), ('FRIEND_ACCEPTED_INVITATION_TEMPLATE', 'Accept an invitation to be a Friend'), ('FRIEND_INVITATION_TEMPLATE', 'Invite Friend'), ('LINK_TO_SIGN_IN_TEMPLATE', 'Link to sign in.'), ('MESSAGE_TO_FRIEND_TEMPLATE', 'Message to friend'), ('NOTICE_FRIEND_ENDORSEMENTS_TEMPLATE', 'New opinion from Friend.'), ('NOTICE_VOTER_DAILY_SUMMARY_TEMPLATE', 'Daily summary of activity for the voter.'), ('VERIFY_EMAIL_ADDRESS_TEMPLATE', 'Verify Senders Email Address'), ('SEND_BALLOT_TO_SELF', 'Send ballot to self'), ('SEND_BALLOT_TO_FRIENDS', 'Send ballot to friends'), ('SIGN_IN_CODE_EMAIL_TEMPLATE', 'Send code to verify sign in.')], default='GENERIC_EMAIL_TEMPLATE', max_length=50)),
                ('sender_voter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='sender full name')),
                ('sender_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sender')),
                ('sender_voter_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address for sender')),
                ('recipient_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the recipient if we have it')),
                ('recipient_email_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='email we vote id for recipient')),
                ('recipient_voter_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address for recipient')),
                ('template_variables_in_json', models.TextField(blank=True, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='EmailScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='email subject')),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_html', models.TextField(blank=True, null=True)),
                ('sender_voter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='sender full name')),
                ('sender_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sender')),
                ('sender_voter_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='sender email address')),
                ('recipient_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the recipient')),
                ('recipient_email_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the email')),
                ('recipient_voter_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='recipient email address')),
                ('send_status', models.CharField(choices=[('TO_BE_PROCESSED', 'Message to be processed'), ('BEING_SENT', 'Message being sent'), ('SENT', 'Message sent')], default='TO_BE_PROCESSED', max_length=50)),
                ('email_outbound_description_id', models.PositiveIntegerField(default=0, verbose_name='the internal id of EmailOutboundDescription')),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='SendGridApiCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_action', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('kind_of_action', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('number_of_items_sent_in_query', models.PositiveIntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendGridApiCounterDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_action', models.DateField(verbose_name='date of action')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call')),
            ],
        ),
        migrations.CreateModel(
            name='SendGridApiCounterMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('month_of_action', models.SmallIntegerField(verbose_name='number of the month')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call')),
            ],
        ),
        migrations.CreateModel(
            name='SendGridApiCounterWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('week_of_action', models.SmallIntegerField(verbose_name='number of the week')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call')),
            ],
        ),
    ]
