# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeToVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote id of this pledge')),
                ('voter_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='we vote id for the voter who made the pledge')),
                ('organization_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='we vote id for the organization running pledge campaign')),
                ('voter_guide_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='we vote id for the voter guide of pledge campaign')),
                ('google_civic_election_id', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='google civic election id')),
                ('take_same_positions', models.BooleanField(default=False)),
                ('visible_to_public', models.BooleanField(default=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date entered')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
