# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_action', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
                ('kind_of_action', models.CharField(choices=[('RETRIEVE_UPDATE_DATA_FROM_TWITTER', 'Retrieve updated data from Twitter'), ('RETRIEVE_POSSIBLE_FACEBOOK_PHOTOS', 'Retrieve possible Facebook photos'), ('RETRIEVE_POSSIBLE_GOOGLE_LINKS', 'Retrieve possible google links'), ('RETRIEVE_POSSIBLE_TWITTER_HANDLES', 'Retrieve possible twitter handles'), ('STOP_BULK_SEARCH_TWITTER_LINK_POSSIBILITY', 'Stop search for Bulk twitter links')], max_length=50, null=True, verbose_name='kind of action to take')),
                ('candidate_campaign_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='candidate we vote id')),
                ('organization_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='we vote id for the org owner')),
                ('number_of_results', models.PositiveIntegerField(default=0, null=True, verbose_name='number of results')),
                ('status', models.TextField(blank=True, default='', null=True, verbose_name='Request status message')),
            ],
        ),
        migrations.CreateModel(
            name='WeVoteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='setting name')),
                ('value_type', models.CharField(choices=[('S', 'String'), ('I', 'Integer'), ('B', 'Boolean')], default='S', max_length=1, verbose_name='value_type')),
                ('string_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='string value')),
                ('integer_value', models.BigIntegerField(blank=True, null=True, verbose_name='integer value')),
                ('boolean_value', models.BooleanField(blank=True, default=None, null=True, verbose_name='boolean value')),
            ],
        ),
    ]
