# Generated by Django 3.2.13 on 2022-06-10 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAuthResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_device_id', models.CharField(max_length=255, unique=True, verbose_name='voter_device_id initiating Facebook Auth')),
                ('datetime_of_authorization', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('facebook_access_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='accessToken from Facebook')),
                ('facebook_expires_in', models.IntegerField(blank=True, null=True, verbose_name='expiresIn from Facebook')),
                ('facebook_signed_request', models.TextField(blank=True, null=True, verbose_name='signedRequest from Facebook')),
                ('facebook_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='facebook big integer id')),
                ('facebook_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='facebook email address')),
                ('facebook_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name from Facebook')),
                ('facebook_middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name from Facebook')),
                ('facebook_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name from Facebook')),
                ('facebook_profile_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of voter&apos;s image from facebook')),
                ('facebook_background_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of voter&apos;s background &apos;cover&apos; image from facebook         (like the twitter banner photo)')),
                ('facebook_background_image_offset_x', models.IntegerField(blank=True, default=0, null=True, verbose_name='x offset of facebook cover image')),
                ('facebook_background_image_offset_y', models.IntegerField(blank=True, default=0, null=True, verbose_name='y offset of facebook cover image')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookFriendsUsingWeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id_of_me', models.BigIntegerField(verbose_name='facebook id of viewer')),
                ('facebook_id_of_my_friend', models.BigIntegerField(verbose_name='facebook id of my friend')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookLinkToVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(max_length=255, unique=True, verbose_name='we vote id for the email owner')),
                ('facebook_user_id', models.BigIntegerField(unique=True, verbose_name='facebook big integer id')),
                ('secret_key', models.CharField(max_length=255, unique=True, verbose_name='secret key to verify ownership facebook account')),
                ('date_last_changed', models.DateTimeField(auto_now=True, verbose_name='date last changed')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookMessageOutboundDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_send_template', models.CharField(choices=[('GENERIC_EMAIL_FACEBOOK_TEMPLATE', 'Generic Email'), ('FRIEND_INVITATION_FACEBOOK_TEMPLATE', 'Invite Friend')], default='GENERIC_EMAIL_FACEBOOK_TEMPLATE', max_length=50)),
                ('sender_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the sender')),
                ('recipient_voter_we_vote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote id for the recipient if we have it')),
                ('recipient_facebook_id', models.BigIntegerField(blank=True, null=True, verbose_name='facebook big integer id')),
                ('recipient_facebook_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='facebook email address')),
                ('recipient_fb_username', models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', message='Only alphanumeric characters are allowed.')])),
                ('send_status', models.CharField(choices=[('TO_BE_PROCESSED', 'Message to be processed'), ('BEING_SENT', 'Message being sent'), ('SENT', 'Message sent')], default='TO_BE_PROCESSED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_id', models.BigIntegerField(verbose_name='facebook id of user')),
                ('facebook_user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User name from Facebook')),
                ('facebook_user_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's first_name from Facebook")),
                ('facebook_user_middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's middle_name from Facebook")),
                ('facebook_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='facebook email address')),
                ('facebook_user_location_id', models.BigIntegerField(null=True, verbose_name='location id of Facebook user')),
                ('facebook_user_location_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's location name from Facebook")),
                ('facebook_user_gender', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's gender from Facebook")),
                ('facebook_user_birthday', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's birthday from Facebook")),
                ('facebook_user_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's last_name from Facebook")),
                ('facebook_profile_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of voter image from facebook')),
                ('facebook_background_image_url_https', models.URLField(blank=True, null=True, verbose_name='url of cover image from facebook')),
                ('facebook_background_image_offset_x', models.IntegerField(blank=True, default=0, null=True, verbose_name='x offset of facebook cover image')),
                ('facebook_background_image_offset_y', models.IntegerField(blank=True, default=0, null=True, verbose_name='y offset of facebook cover image')),
                ('we_vote_hosted_profile_image_url_large', models.URLField(blank=True, null=True, verbose_name='we vote hosted large image url')),
                ('we_vote_hosted_profile_image_url_medium', models.URLField(blank=True, null=True, verbose_name='we vote hosted medium image url')),
                ('we_vote_hosted_profile_image_url_tiny', models.URLField(blank=True, null=True, verbose_name='we vote hosted tiny image url')),
                ('facebook_user_about', models.CharField(blank=True, max_length=255, null=True, verbose_name="User's About from Facebook")),
                ('facebook_user_is_verified', models.BooleanField(default=False, verbose_name='User is verfired from Facebook')),
                ('facebook_user_friend_total_count', models.BigIntegerField(null=True, verbose_name='total count of friends from facebook')),
            ],
        ),
    ]
