# Generated by Django 3.2.13 on 2022-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_full_url', models.URLField(blank=True, max_length=255, null=True)),
                ('shared_item_code_no_opinions', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('shared_item_code_all_opinions', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('shared_by_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('shared_by_organization_type', models.CharField(choices=[('C', 'Corporation'), ('G', 'Group'), ('I', 'Individual'), ('NW', 'News Corporation'), ('NP', 'Nonpartisan'), ('C3', 'Nonprofit 501c3'), ('C4', 'Nonprofit 501c4'), ('P', 'Political Action Committee'), ('PF', 'Public Figure'), ('TA', 'Trade Association or Union'), ('U', 'Unknown Type'), ('O', 'Group - Organization')], default='U', max_length=2, verbose_name='type of org')),
                ('shared_by_organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('shared_by_state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('site_owner_organization_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('google_civic_election_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hide_introduction', models.BooleanField(default=False)),
                ('is_ballot_share', models.BooleanField(default=False)),
                ('is_campaignx_share', models.BooleanField(default=False)),
                ('is_candidate_share', models.BooleanField(default=False)),
                ('is_measure_share', models.BooleanField(default=False)),
                ('is_office_share', models.BooleanField(default=False)),
                ('is_organization_share', models.BooleanField(default=False)),
                ('is_ready_share', models.BooleanField(default=False)),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('measure_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('office_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_first_shared', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('year_as_integer', models.PositiveIntegerField(db_index=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SharedLinkClicked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_full_url', models.URLField(blank=True, max_length=255, null=True)),
                ('shared_by_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('shared_by_organization_type', models.CharField(choices=[('C', 'Corporation'), ('G', 'Group'), ('I', 'Individual'), ('NW', 'News Corporation'), ('NP', 'Nonpartisan'), ('C3', 'Nonprofit 501c3'), ('C4', 'Nonprofit 501c4'), ('P', 'Political Action Committee'), ('PF', 'Public Figure'), ('TA', 'Trade Association or Union'), ('U', 'Unknown Type'), ('O', 'Group - Organization')], default='U', max_length=2, verbose_name='type of org')),
                ('shared_by_organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('shared_by_state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('viewed_by_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('viewed_by_organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('viewed_by_state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('shared_item_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('shared_item_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('site_owner_organization_we_vote_id', models.CharField(max_length=255, null=True)),
                ('include_public_positions', models.BooleanField(default=False)),
                ('include_friends_only_positions', models.BooleanField(default=False)),
                ('date_clicked', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('year_as_integer', models.PositiveIntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedPermissionsGranted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('shared_by_organization_type', models.CharField(choices=[('C', 'Corporation'), ('G', 'Group'), ('I', 'Individual'), ('NW', 'News Corporation'), ('NP', 'Nonpartisan'), ('C3', 'Nonprofit 501c3'), ('C4', 'Nonprofit 501c4'), ('P', 'Political Action Committee'), ('PF', 'Public Figure'), ('TA', 'Trade Association or Union'), ('U', 'Unknown Type'), ('O', 'Group - Organization')], default='U', max_length=2, verbose_name='type of org')),
                ('shared_by_organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('shared_to_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('shared_to_organization_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('google_civic_election_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('year_as_integer', models.PositiveIntegerField(db_index=True, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
                ('include_friends_only_positions', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuperShareEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sent_to_email', models.DateTimeField(default=None, null=True)),
                ('email_address_text', models.TextField(blank=True, db_index=True, null=True)),
                ('google_contact_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('recipient_display_name', models.CharField(default=None, max_length=255, null=True)),
                ('recipient_first_name', models.CharField(default=None, max_length=255, null=True)),
                ('recipient_last_name', models.CharField(default=None, max_length=255, null=True)),
                ('recipient_state_code', models.CharField(db_index=True, default=None, max_length=2, null=True)),
                ('recipient_voter_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('shared_by_voter_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('super_share_item_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperShareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx_news_item_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaignx_we_vote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_sent_to_email', models.DateTimeField(default=None, null=True)),
                ('destination_full_url', models.URLField(blank=True, max_length=255, null=True)),
                ('in_draft_mode', models.BooleanField(db_index=True, default=True)),
                ('personalized_message', models.TextField(blank=True, db_index=True, null=True)),
                ('personalized_subject', models.TextField(blank=True, db_index=True, null=True)),
                ('shared_by_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('site_owner_organization_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
    ]
